/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lafontana.games.game2;

import javax.swing.JOptionPane;

/**
 *
 * @author luis
 */
public class MainGame2 extends javax.swing.JFrame {

    Question q1;
    Question q2;
    Question q3;
    Question q4;
    Question q5;
    int level = 1;
    double score = 0;

    /**
     * Creates new form Main
     */
    public MainGame2() {
        initComponents();

        q1 = new Question("Selecciona la respuesta correcta ", "/images/ejercicio 1.png", "/images/Respuesta 1.1.png", "/images/Respuesta 1.2.png", "/images/Respuesta 1.3.png", "/images/Respuesta 1.4.png");
        q2 = new Question("Selecciona la respuesta correcta ", "/images/Ejercicio 2.png", "/images/Respuesta 2.2.png", "/images/Respuesta 2.1.png", "/images/Respuesta 2.3.png", "/images/Respuesta 2.4.png");
        q3 = new Question("Selecciona la respuesta correcta ", "/images/Ejercicio 3.png", "/images/Respuesta 3.1.png", "/images/Respuesta 3.2.png", "/images/Respuesta 3.3.png", "/images/Respuesta 3.4.png");
        q4 = new Question("Selecciona la respuesta correcta ", "/images/Ejercicio 4.png", "/images/Respuesta 4.1.png", "/images/Respuesta 4.2.png", "/images/Respuesta 4.3.png", "/images/Respuesta 4.4.png");
        q5 = new Question("Selecciona la respuesta correcta ", "/images/Ejercicio 5.png", "/images/Respuestas 5.4.png", "/images/Respuesta 5.2.png", "/images/Respuesta 5.3.png", "/images/Respuestas 5.1.png");
        
        if (level == 1) {
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(q1.getImgEnunciado())));
        }
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ejercicio 1.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/respuesta 1.1.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Respuesta 1.2.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Respuestas 1.3.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Respuestas 1.4.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setText("Score:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel4)
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel5)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void update(){
        jLabel7.setText(score+" ");
        switch(level){
            case 0:
                
                break;
            case 1:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(q1.getImgEnunciado())));//enunciado
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(q1.getImgOpcion1())));//opcion1
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(q1.getImgOpcion2())));//opcion2
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(q1.getImgOpcion3())));//opcion3
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(q1.getImgOpcion4())));//opcion4
                break;
            case 2:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(q2.getImgEnunciado())));//enunciado
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(q2.getImgOpcion1())));//opcion1
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(q2.getImgOpcion2())));//opcion2
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(q2.getImgOpcion3())));//opcion3
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(q2.getImgOpcion4())));
                break;
            case 3:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(q3.getImgEnunciado())));
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(q3.getImgOpcion1())));//opcion1
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(q3.getImgOpcion2())));//opcion2
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(q3.getImgOpcion3())));//opcion3
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(q3.getImgOpcion4())));
                break;
            case 4:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(q4.getImgEnunciado())));
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(q4.getImgOpcion1())));//opcion1
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(q4.getImgOpcion2())));//opcion2
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(q4.getImgOpcion3())));//opcion3
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(q4.getImgOpcion4())));
                break;
            case 5:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(q5.getImgEnunciado())));
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(q5.getImgOpcion1())));//opcion1
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(q5.getImgOpcion2())));//opcion2
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(q5.getImgOpcion3())));//opcion3
                jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource(q5.getImgOpcion4())));
                break;
        }
             
    }
    
    
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        switch(level){
            case 0:
                
                break;
            case 1:
                score += 100;
                JOptionPane.showMessageDialog(null, "Buen trabajo +100");
                level = 2;
                update();
                break;
            case 2:
                score -= 50;
                JOptionPane.showMessageDialog(null, "Intentalo de nuevo -50");
                update ();
                break;
            case 3:
                score += 100;
                JOptionPane.showMessageDialog(null, "Buen trabajo +100 ");
                level = 4;
                update ();
                break;
            case 4:
                score -= 50;
                JOptionPane.showMessageDialog(null, "Intentalo de nuevo -50");
                update ();
                break;
            case 5:
                score -= 50;
                JOptionPane.showMessageDialog(null, "Intentalo de nuevo -50");
                update ();
                break;
        }
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       switch(level){
            case 0:
                
                break;
            case 1:
                score -= 50;
                JOptionPane.showMessageDialog(null, "Intentalo de nuevo -50");
                update();
                break;
            case 2:
                score += 100;
                JOptionPane.showMessageDialog(null, "Buen trabajo +100 ");
                level = 3;
                update ();
                break;
            case 3:
                score -= 50;
                JOptionPane.showMessageDialog(null, "Intentalo de nuevo -50");
                update ();
                break;
            case 4:
                score -= 50;
                JOptionPane.showMessageDialog(null, "Intentalo de nuevo -50");
                update ();
                break;
            case 5:
                score -= 50;
                JOptionPane.showMessageDialog(null, "Intentalo de nuevo -50");
                update ();
                break;
        } 
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        switch(level){
            case 0:
                
                break;
            case 1:
                score -= 50;
                JOptionPane.showMessageDialog(null, "Intentalo de nuevo -50");
                update();
                break;
            case 2:
                score -= 50;
                JOptionPane.showMessageDialog(null, "Intentalo de nuevo -50");
                update ();
                break;
            case 3:
                score -= 50;
                JOptionPane.showMessageDialog(null, "Intentalo de nuevo -50");
                update ();
                break;
            case 4:
                score += 100;
                JOptionPane.showMessageDialog(null, "Buen trabajo +100");
                level = 5;
                update ();
                break;
            case 5:
                score -= 50;
                JOptionPane.showMessageDialog(null, "Intentalo de nuevo -50");
                update ();
                break;
        }
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
                                 
        switch(level){
            case 0:
                
                break;
            case 1:
                score -= 50;
                JOptionPane.showMessageDialog(null, "Intentalo de nuevo -50");
                update();
                break;
            case 2:
                score -= 50;
                JOptionPane.showMessageDialog(null, "Intentalo de nuevo -50");
                update ();
                break;
            case 3:
                score -= 50;
                JOptionPane.showMessageDialog(null, "Intentalo de nuevo -50");
                update ();
                break;
            case 4:
                score -= 50;
                JOptionPane.showMessageDialog(null, "Intentalo de nuevo -50");
                update ();
                break;
            case 5:
                score += 100;
                JOptionPane.showMessageDialog(null, "Buen trabajo +100");
                level = 6;
                update ();
                break;
        }
        
    
    }//GEN-LAST:event_jLabel5MouseClicked

     
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
